### ISSUE TITLE
Analytics

### ISSUE THREAD

**Issue by kanodiaayush** [overshard/timelite#48] opened 2021-01-15 01:25 UTC
Is there a way to get summary information about which tags I spent my most time on and such?

**Comment by overshard** [comment] 2021-04-06 18:44
Hello, I appreciate the input! I believe this is a duplicate of issue #5 . I agree some analytics/stats would be cool and useful. If you have any suggestions please add them to that issue.

**Closed by overshard** 2021-04-06 18:44 UTC
Labels: duplicate
